apiVersion: batch/v1
kind: Job
metadata:
  namespace: example06
  generateName: resource-b
  labels:
    codefresh.io/cert: enable-job
  annotations:
    argocd.argoproj.io/sync-wave: "20"
    argocd.argoproj.io/hook: Sync
spec:
  template:
    spec:
      containers:
      - name: dummy-message
        image: alpine
        command:
          - "sleep"
          - "3"
      restartPolicy: Never
  backoffLimit: 2    
