apiVersion: batch/v1
kind: Job
metadata:
  namespace: example06
  generateName: grafana-notify-
  labels:
    codefresh.io/cert: grafana-job
  annotations:
    argocd.argoproj.io/sync-wave: "-10"
    argocd.argoproj.io/hook: SyncFail
spec:
  template:
    spec:
      containers:
      - name: dummy-run
        image: alpine
        command:
          - "sleep123"
          - "10"
      restartPolicy: Never
  backoffLimit: 2    
